spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/warehouse_db
    username: user
    password: pw

  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8081

warehouse:
  productCsv: ${PRODUCT_CSV:src/main/resources/products.csv}
  componentCsv: ${COMPONENT_CSV:src/main/resources/components.csv}
